### ISSUE TITLE
Question on using entity browser

### ISSUE THREAD

**Issue by Neitex** [JetBrains/xodus-entity-browser#38]
Hello! I've created Xodus DB using Xodus-DNQ definitions and I've checked that it works (data is saved successfully and can be obtained later), however, when I try to add same database to Entity Browser, it opens DB but says "Database is empty - you can add ", which is strange, since there IS data in DB. 
When DB is opened in write-mode, it prompts me to create new Entity Type. I've tried to enter models names into corresponding field, but then it still shows "Nothing was found". 
What am I missing? Thanks in advance!

**Comment by lehvolk** [comment]
Could you please check which key is used for store in dnq and which you pass in entity browser.

**Comment by Neitex** [comment]
I am sorry - what is key? :)
I don't remember setting it explicitly.

**Comment by Neitex** [comment]
Oh, I got it - for everyone else wondering - key is `environmentName` in 
```kotlin
val store = StaticStoreContainer.init(
            dbFolder = databaseHome,
            environmentName = "db"
    )
```
(Sample Application in Xodus-DNQ GH Pages)
Thanks for help!

**Comment by lehvolk** [comment]
Then you need to pass "db" as a key into UI:
<img width="594" alt="Screenshot 2022-03-09 at 16 36 57" src="https://user-images.githubusercontent.com/6284727/157452638-e7da14e0-1dab-4fe6-963c-ccaf97e9fcd4.png">
